label: Address dialog
status: ready
context:
  id: be
  close: Dialog schliessen
  addresses:
  - title: Grüne Kanton Bern
    address: Musterstrasse 99<br>0000 Beispielort
    phone: 012 345 67 89
    link-button:
      label: E-Mail senden
      link: mailto:party@example.com
      modifiers:
      - grey
    button:
      label: Website
      link: https://example.com
      modifiers:
      - outline
      - full-width
  - title: Grünalternative Partei Bern
    address: Musterstrasse 99<br>0000 Beispielort
    phone: 012 345 67 89
    link-button:
      label: E-Mail senden
      link: mailto:party@example.com
      modifiers:
      - grey
    button:
      label: Website
      link: https://example.com
      modifiers:
      - outline
      - full-width
  links:
  - label: Junge Grüne Bern
    link: https://example.com