dist: xenial

sudo: true

branches:
  only:
    - master
    - styleguide

cache:
  directories:
    - node_modules
    - vendor

before_install:
  # install yarn and php
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update
  - sudo apt-get install -y yarn

  # install composer
  - sudo apt-get install -y php
  - curl -sS https://getcomposer.org/installer | php
  - sudo mv composer.phar /usr/local/bin/composer
  - chmod +x /usr/local/bin/composer

install:
  - yarn

script:
  - yarn gulp sg:custom
  - yarn fractal:build
  - yarn make:release

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: styleguide/dist/build
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master|styleguide$
      repo: grueneschweiz/2018.gruene.ch

  - provider: releases
    api_key:
      secure: YhvZmic9GQJUQrDTZZ0jr3QTIbqcsfftOLlkmlVAwMcK43qin83rp0COxzMzzt7HIOg23r02cnM4Le0hyZBP8aDafEzGbH+46yeJLmcT74FCRheswkNUfSBV1T6Mz04+FQL8GRdLcbzyTIICJAbskOpz5dXEyUBy4/gaUy7VNJJnffeT6U56h4QGOczwJeQK7O29PnaRjNqAFb6BzKa24QwTD7KXYZ0kCYbdwEmIXrG5L4nx6M216tZXADa1dXNVerJ1eoP7tbq5CYjB/VoWgOVirwfIsO6dEsZKpFs68afSUcDQqOHd1cV04XfDx4au0XM5M7xk8/Zy/W642ii4o+6nFz7gjDI2kGe/VqVmHiutGPCVOrhC8EIrRvroVhxSdHTW2PnLmKxalUtXjmCWdKQnEZQLGUSFsDSEBg6xEzdEcPR3NpJlq6iGpFRmPfFxFUVI3rCbId4DLKfK07aDpl3qQRx7go3qCgDIvBXfc8VS+LHONP1fjxEdJAYQxV1YAvNeMvs9NIKf74kXhjQzPgGlPP9L/JQ7Zsj7tyMY1VVHa9nHpznxSjlOjj24U6GiiZtGramWedCsjSWC8IoYeRRZrs/M5V6cXDfFXbV9o50APQ+BJDefgpqhoTHH8lXYnmsMP9+v0VRl+2yzFRLgNoTDeG78vIQG1VEmzRuMA+k=
    file: release.zip
    skip_cleanup: true
    on:
      branch: master
      tags: true
      repo: grueneschweiz/2018.gruene.ch

