volumes:
  database:

services:
  wordpress:
    depends_on:
      - db
    build:
      context: .
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    ports:
      # MUST be on port 80, because multisite
      # doesn't support ports in base url
      - "80:80"
    working_dir: /var/www/html
    volumes:
      - ./wordpress/wp-content/:/var/www/html/wp-content:cached
      - ./wordpress/.htaccess:/var/www/html/.htaccess
      - ./scripts/php.ini:/usr/local/etc/php/php.ini
      - ./scripts/ssmtp.conf:/etc/ssmtp/ssmtp.conf
    container_name: wp_docker_les_verts
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
      PHP_IDE_CONFIG: serverName=Docker
    command: [ "apache2-foreground" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mariadb:10.6
    volumes:
      - database:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8181:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: wordpress
      UPLOAD_LIMIT: 1G

  mailhog:
    image: mailhog/mailhog
    command: ["-smtp-bind-addr", "0.0.0.0:25"]
    user: root
    expose:
      - 25
      - 8025
    ports:
      - 8025:8025
