label: Footer contact
status: ready
display:
  padding: 40px
context:
  title: Kontakt
  address:
    title: Grüne Scheiz<br>Les Verts suisses
    address: Waisenhausplatz 21<br>3011 Bern
    phone: 031 326 66 00
    bank: Postkonto 80-26747-3
    button:
      label: E-Mail senden
      link: "mailto:gruene@gruene.ch"
  facebook:
    type: facebook
    link: "https://www.facebook.com/gruenelesverts/"
  twitter:
    type: twitter
    link: "https://twitter.com/GrueneCH"