label: Header
status: wip
context:
  branding:
    unbreakables:
      - Ökologisch konsequent.
      - Sozial engagiert.
      - Global solidarisch.
    logo:
      de: true
      white: true
      modifiers:
        - white