label: Bars
status: ready
default: right
context:
  modifiers:
  - left
  bars:
  - bar-1:
    label: Engagiere dich
    modifiers:
    - green
    - left
    - no-sanuk
  - bar-2:
    label: f체r Fair-Food
    modifiers:
    - magenta
    - left
    - no-sanuk
  - bar-3:
    label: zusammen die Welt ver채ndern
    modifiers:
    - white
    - left
    - subline
    - no-sanuk
variants:
  - name: right
    context:
      modifiers:
      - right
      bars:
      - bar-1:
        label: Engagiere dich
        modifiers:
        - green
        - right
        - no-sanuk
      - bar-2:
        label: f체r Fair-Food
        modifiers:
        - magenta
        - right
        - no-sanuk
      - bar-3:
        label: zusammen die Welt ver채ndern
        modifiers:
        - white
        - right
        - subline
        - no-sanuk
