label: Post Link
status: ready
default: Post whithout excerpt
context:
  post: true
  link: '#'
  title: Für nachhaltige Sportveranstaltungen und ein Graubünden ohne Olympische Spiele
  date: 17. Januar 2016
  categories:
  - Resolutionen
  - Sport
  modifiers:
  - post
variants:
- name: Post with excerpt
  context:
    post: true
    has_excerpt: true
    excerpt: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum
    modifiers:
    - post
    - excerpt
- name: Page
  context:
    page: true
    date: ''
    modifiers:
    - page
- name: External Link
  context:
    external: true
    target: _blank
    modifiers:
    - link
