label: Front article
status: wip
default: double
context:
  modifiers:
    - double
  cat-title:
    label: Kampagnen
    url: '#'
  articles:
    - article-1:
      modifiers:
        - image-second
      url: '#'
      title: "Gleichstellung: Ein Schwerpunkt der Grünen - seit ihrer Gründung"
      text: "Die Gleichstellung von Mann und Frau ist seit 1981 in der Verfassung verankert und seit 1996 im Gleichstellungsgesetz festgeschrieben. In der Realität ist die Gleichstellung jedoch noch lange nicht erreicht. Frauen sind nach wie vor untervertreten in Kaderpositionen, verdienen deutlich weniger als Männer. Ebenso arbeiten fast alle Männer Vollzeit, aber nur jede zweite Frau."
      has-img: true
      img:
        url: '#'
        image-src: "/img/wheat.jpg"
        alt: Symbolbild Fair-Food
        title: Fair schmeckt besser
    - article-2:
      modifiers:
        - no-image
      url: '#'
      title: "Gleichstellung: Ein Schwerpunkt der Grünen - seit ihrer Gründung"
      text: "Die Gleichstellung von Mann und Frau ist seit 1981 in der Verfassung verankert und seit 1996 im Gleichstellungsgesetz festgeschrieben. In der Realität ist die Gleichstellung jedoch noch lange nicht erreicht. Frauen sind nach wie vor untervertreten in Kaderpositionen, verdienen deutlich weniger als Männer. Ebenso arbeiten fast alle Männer Vollzeit, aber nur jede zweite Frau."
      has-img: false
variants:
  - name: single
    context:
      single: true
      modifiers:
        - single
      cat-title:
        label: Kampagne
        url: '#'
      articles:
        - article-1:
          modifiers:
            - image-second
          url: '#'
          title: "Gleichstellung: Ein Schwerpunkt der Grünen - seit ihrer Gründung"
          text: "Die Gleichstellung von Mann und Frau ist seit 1981 in der Verfassung verankert und seit 1996 im Gleichstellungsgesetz festgeschrieben. In der Realität ist die Gleichstellung jedoch noch lange nicht erreicht. Frauen sind nach wie vor untervertreten in Kaderpositionen, verdienen deutlich weniger als Männer. Ebenso arbeiten fast alle Männer Vollzeit, aber nur jede zweite Frau."
          has-img: true
          img:
            url: '#'
            image-src: "/img/wheat.jpg"
            alt: Symbolbild Fair-Food
            title: Fair schmeckt besser
      cta:
        label: Aktiv werden
        modifiers:
          - secondary
      cta-help-text: Ich will mich für Gleichstellung einsetzen
