label: Submenu
status: ready
context:
  title: 'Submenu'
  url: '#'
  items:
    - label: Fair-Food
      url: '#'
    - label: Petition «Nein zur Lex Beznau»
      url: '#'
    - label: Referendum gegen Versicherungsspione
      url: '#'
    - label: Events
      url: '#'
variants:
  - name: Featured
    context:
      modifiers:
        - featured
      featured: true
      img:
        src: "/img/wheat.jpg"
        alt: Symbolbild Fair-Food
      cat-title:
        label: Fair-Food-Initiative
      title: Fair schmeckt besser!
      text: Umweltfreundlich und fair hergestellte Lebensmittel – dies wollen die Grünen mit der Fair-Food-Initiative erreichen.
      button:
        label: Kampagne anzeigen