context:
  groups:
    - name: Actions
      icons:
        - close
        - slide
    - name: Miscellaneous
      icons:
        - testimony
        - glass
        - hamburger
        - quote
        - arrow
    - name: Social Media / Contact
      icons:
        - facebook
        - twitter
        - email
        - mobile
