context:
  groups:
    - name: Actions
      icons:
        - close
        - slide
        - glass
        - plus
        - next
        - last
    - name: Miscellaneous
      icons:
        - testimony
        - quote
        - arrow
    - name: Social Media / Contact
      icons:
        - facebook
        - twitter
        - mail
        - mobile
