context:
  groups:
    - name: Actions
      icons:
        - close
        - slide
        - glass
        - plus
        - next
        - last
    - name: Miscellaneous
      icons:
        - testimony
        - quote
        - arrow
        - clock
        - location
    - name: Social Media / Contact
      icons:
        - facebook
        - tiktok
        - twitter
        - linkedin
        - instagram
        - mail
        - youtube
        - mastodon
        - tumblr
        - mobile
        - telegram
        - link
        - facebook--no-outline
        - twitter--no-outline
        - mail--no-outline
        - whatsapp--no-outline
