context:
  colors:
    - title: Primary
      values:
        primary: "#84B414"
        primary-dark: "#516F0A"
    - title: Secondary
      values:
        secondary: "#E10078"
        secondary-dark: "#B1025F"
    - title: Text
      values:
        text: "#333333"
        text-light: "#4E4E4E"
    - title: Monochrome
      values:
        white: "#FFFFFF"
        grey-1: "#F9F9F9"
        grey-2: "#E2E2E2"
        black: "#000000"
