label: Link Button
status: ready
display:
  padding: 40px
context:
  label: Weiterlesen
variants:
  - name: Grey
    context:
      modifiers:
        - grey
  - name: White
    display:
      background-color: "#E2E2E2"
    context:
      modifiers:
        - white