label: Link Button
status: ready
display:
  margin: 40px
context:
  label: Weiterlesen
variants:
  - name: Grey
    context:
      modifiers:
        - grey
  - name: White
    context:
      modifiers:
        - white