label: Menu
status: wip
context:
  nav-items:
    - title: Aktuelles
      section-items:
        - title: Kampagnen und Events
          items:
            - label: Fair-Food
            - label: Petition «Nein zur Lex Beznau»
            - label: Referendum gegen Versicherungsspione
            - label: Events
        - title: Abstimmungsempfehlungen
          items:
            - label: Gegenvorschlag Veloinitiative
            - label: Ernährungssouveränität
            - label: Fair-Food
        - title: Medienmitteilungen
        - title: Fair-Food-Initiative
          featured: true
          img:
            src: "/img/wheat.jpg"
            alt: Symbolbild Fair-Food
          cat-title:
            label: Fair-Food-Initiative
          text: Umweltfreundlich und fair hergestellte Lebensmittel – dies wollen die Grünen mit der Fair-Food-Initiative erreichen.
          button:
            label: Kampagne anzeigen
          modifiers:
            - featured
    - title: Positionen
    - title: Die Grünen
    - title: Publikationen
    - title: Kontakt
  languages:
    - de
    - fr
  search: Suche
  logo:
    de: true
    title: Logo Grüne Schweiz
  button:
    label: Mitmachen
    modifiers:
      - outline
      - secondary