label: List Header
status: ready
context:
  counter: 82
  title: 'Suchresultate zu <span class="m-list-header__term">Atomie</span> in der Kategorie <span class="m-list-header__term">Klima und Energie</span>'
  criteria-desc: "Nach Kategorie filtern:"
  button:
    label: Alle Resultate Anzeigen
    modifiers:
      - outline
  criteria:
    - name: Klima und Energie
      link: "#asdf"
      active: true
    - name: Atom
      link: "#asdf"
    - name: Energiewende
      link: "#lkjh"
