<?php

if ( function_exists( 'acf_add_local_field_group' ) ):
	
	acf_add_local_field_group( array(
		'key'                   => 'group_5ab227ac7540e',
		'title'                 => __( 'Local form settings', THEME_DOMAIN ),
		'fields'                => array(
			array(
				'key'               => 'field_5afc366ed02dc',
				'label'             => __( 'Which type of form is it?', THEME_DOMAIN ),
				'name'              => 'which_type_of_form',
				'type'              => 'radio',
				'instructions'      => '',
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'email' => __( 'Send form result by email', THEME_DOMAIN ),
					'cm'    => __( 'Send form result to Campaign Monitor only', THEME_DOMAIN ),
					'news'  => __( 'Use a "Subscribe to Newsletter" checkbox (will also send to Campaign Monitor)',
						THEME_DOMAIN ),
				),
				'allow_null'        => 0,
				'other_choice'      => 0,
				'save_other_choice' => 0,
				'default_value'     => '',
				'layout'            => 'vertical',
				'return_format'     => 'value',
			),
			array(
				'key'               => 'field_5afd348dd414a',
				'label'             => '',
				'name'              => 'checkbox_settings',
				'type'              => 'group',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5afc366ed02dc',
							'operator' => '==',
							'value'    => 'news',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'block',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5afc3d77bfbd2',
						'label'             => __( 'Checkbox settings', THEME_DOMAIN ),
						'name'              => '',
						'type'              => 'tab',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => array(
							array(
								array(
									'field'    => 'field_5afc366ed02dc',
									'operator' => '==',
									'value'    => 'news',
								),
							),
						),
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'placement'         => 'left',
						'endpoint'          => 0,
					),
					array(
						'key'               => 'field_5afd348dd414b',
						'label'             => __( 'Label', THEME_DOMAIN ),
						'name'              => 'label',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '50',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => 'I subscribe to the newsletter',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
				),
			),
			array(
				'key'               => 'field_5afc3d4bbfbd0',
				'label'             => '',
				'name'              => 'campaign_monitor_settings',
				'type'              => 'group',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5afc366ed02dc',
							'operator' => '!=',
							'value'    => 'email',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'block',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5afd3490d414d',
						'label'             => __( 'Campaign Monitor settings', THEME_DOMAIN ),
						'name'              => '',
						'type'              => 'tab',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'placement'         => 'left',
						'endpoint'          => 0,
					),
					array(
						'key'               => 'field_5afc3bd4bfbca',
						'label'             => __( 'Subscribers list', THEME_DOMAIN ),
						'name'              => 'subscribers_list',
						'type'              => 'select',
						'instructions'      => __( 'Choose below which list from Campaign Monitor you want to link to…',
							THEME_DOMAIN ),
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '40',
							'class' => '',
							'id'    => '',
						),
						'choices'           => array(),
						'default_value'     => array(),
						'allow_null'        => 0,
						'multiple'          => 0,
						'ui'                => 0,
						'ajax'              => 0,
						'return_format'     => 'value',
						'placeholder'       => '',
					),
					array(
						'key'               => 'field_5afc3cedbfbce',
						'label'             => __( 'Source fields', THEME_DOMAIN ),
						'name'              => 'source_fields',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'block',
						'sub_fields'        => array(
							array(
								'key'               => 'field_5afc4272f8897',
								'label'             => '',
								'name'              => '',
								'type'              => 'message',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'message'           => __( 'Campaign Monitor needs two types of data:
* the email of the user
* the name of the user

To correctly send data to the Campaign Monitor, please select below where to get this email from the form details.',
									THEME_DOMAIN ),
								'new_lines'         => 'wpautop',
								'esc_html'          => 0,
							),
							array(
								'key'               => 'field_5afc3c59bfbcb',
								'label'             => __( 'Email field', THEME_DOMAIN ),
								'name'              => 'email_field_source',
								'type'              => 'select',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '33',
									'class' => '',
									'id'    => '',
								),
								'choices'           => array(),
								'default_value'     => array(),
								'allow_null'        => 0,
								'multiple'          => 0,
								'ui'                => 0,
								'ajax'              => 0,
								'return_format'     => 'value',
								'placeholder'       => '',
							),
							array(
								'key'               => 'field_5afc3c81bfbcc',
								'label'             => __( 'First Name', THEME_DOMAIN ),
								'name'              => 'first_name_field_source',
								'type'              => 'select',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '33',
									'class' => '',
									'id'    => '',
								),
								'choices'           => array(),
								'default_value'     => array(),
								'allow_null'        => 0,
								'multiple'          => 0,
								'ui'                => 0,
								'ajax'              => 0,
								'return_format'     => 'value',
								'placeholder'       => '',
							),
							array(
								'key'               => 'field_5afc3ccfbfbcd',
								'label'             => __( 'Last Name', THEME_DOMAIN ),
								'name'              => 'last_name_field_source',
								'type'              => 'select',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '33',
									'class' => '',
									'id'    => '',
								),
								'choices'           => array(),
								'default_value'     => array(),
								'allow_null'        => 0,
								'multiple'          => 0,
								'ui'                => 0,
								'ajax'              => 0,
								'return_format'     => 'value',
								'placeholder'       => '',
							),
						),
					),
				),
			),
			array(
				'key'               => 'field_5afc39baa62c7',
				'label'             => '',
				'name'              => 'local_form_settings_group',
				'type'              => 'group',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5afc366ed02dc',
							'operator' => '!=',
							'value'    => 'cm',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'block',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5afd3494d4154',
						'label'             => __( 'Local form settings', THEME_DOMAIN ),
						'name'              => '',
						'type'              => 'tab',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => array(
							array(
								array(
									'field'    => 'field_5afc366ed02dc',
									'operator' => '!=',
									'value'    => 'cm',
								),
							),
						),
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'placement'         => 'left',
						'endpoint'          => 0,
					),
					array(
						'key'               => 'field_5ab227b201b95',
						'label'             => '',
						'name'              => '',
						'type'              => 'message',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => array(
							array(
								array(
									'field'    => 'field_5afc366ed02dc',
									'operator' => '!=',
									'value'    => 'cm',
								),
							),
						),
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'message'           => __( 'The parameters below will replace the global settings.', THEME_DOMAIN ),
						'new_lines'         => 'wpautop',
						'esc_html'          => 0,
					),
					array(
						'key'               => 'field_5ab227c201b96',
						'label'             => '',
						'name'              => '',
						'type'              => 'clone',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'clone'             => array(
							0 => 'field_5a880e1a10cc4',
							1 => 'field_5a880e6310cc5',
							2 => 'field_5a880ed310cc6',
							3 => 'field_5a880ff110cc8',
							4 => 'field_5a88145e726f1',
							5 => 'field_5a8822c3c6318',
							6 => 'field_5a882319c631a',
						),
						'display'           => 'seamless',
						'layout'            => 'block',
						'prefix_label'      => 0,
						'prefix_name'       => 0,
					),
				),
			),
			array(
				'key'               => 'field_5afd40976817a',
				'label'             => '',
				'name'              => 'privacy_group',
				'type'              => 'group',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'block',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5afd40e16817c',
						'label'             => '',
						'name'              => '',
						'type'              => 'clone',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'clone'             => array(
							0 => 'field_5a9s2f6hc34da',
							1 => 'field_5ab255fd48364',
						),
						'display'           => 'seamless',
						'layout'            => 'block',
						'prefix_label'      => 0,
						'prefix_name'       => 0,
					),
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'theme_form',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => 1,
		'description'           => '',
	) );

endif;
