<?php

if ( function_exists( 'acf_add_local_field_group' ) ):
	
	acf_add_local_field_group( array(
		'key'                   => 'group_5a880cad9baac',
		'title'                 => 'Settings',
		'fields'                => array(
			array(
				'key'               => 'field_5a95bda5c34da',
				'label'             => __( 'SMTP', THEME_DOMAIN ),
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 1,
			),
			array(
				'key'               => 'field_5a95bdafc34db',
				'label'             => __( 'Send over SMTP', THEME_DOMAIN ),
				'name'              => 'form_smtp_enabled',
				'type'              => 'true_false',
				'instructions'      => __( 'If yes, send emails using SMTP', THEME_DOMAIN ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'ui'                => 1,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
			),
			array(
				'key'               => 'field_5a95bdf6c34dc',
				'label'             => '',
				'name'              => 'form_smtp',
				'type'              => 'group',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5a95bdafc34db',
							'operator' => '==',
							'value'    => '1',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'block',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5a95be01c34dd',
						'label'             => __( 'Server address', THEME_DOMAIN ),
						'name'              => 'form_smtp_host',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
					array(
						'key'               => 'field_5a95be3dc34de',
						'label'             => __( 'Port', THEME_DOMAIN ),
						'name'              => 'form_smtp_port',
						'type'              => 'number',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '50',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => 465,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'min'               => '',
						'max'               => '',
						'step'              => '',
					),
					array(
						'key'               => 'field_5fbba5dbd1736',
						'label'             => __( 'Security', THEME_DOMAIN ),
						'name'              => 'form_smtp_security',
						'type'              => 'select',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '50',
							'class' => '',
							'id'    => '',
						),
						'choices'           => array(
							'none' => __( 'None', THEME_DOMAIN ),
							'ssl'  => __( 'SSL', THEME_DOMAIN ),
							'tls'  => __( 'TLS', THEME_DOMAIN ),
						),
						'default_value'     => 'ssl',
						'allow_null'        => 0,
						'multiple'          => 0,
						'ui'                => 1,
						'ajax'              => 0,
						'return_format'     => 'value',
						'placeholder'       => '',
					),
					array(
						'key'               => 'field_5a95be77c34df',
						'label'             => __( 'Username', THEME_DOMAIN ),
						'name'              => 'form_smtp_username',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '50',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
					array(
						'key'               => 'field_5a95be8fc34e0',
						'label'             => __( 'Password', THEME_DOMAIN ),
						'name'              => 'form_smtp_password',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '50',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
				),
			),
			array(
				'key'               => 'field_5c0fde4a133b7',
				'label'             => __( 'Webling', THEME_DOMAIN ),
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 1,
			),
			array(
				'key'               => 'field_5c0fde5a133b8',
				'label'             => __( 'API Url', THEME_DOMAIN ),
				'name'              => 'api_url',
				'type'              => 'url',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_5c0fde79133b9',
				'label'             => __( 'API Key (Client Secret)', THEME_DOMAIN ),
				'name'              => 'client_secret',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5c1634144as4f',
				'label'             => __( 'Client Id', THEME_DOMAIN ),
				'name'              => 'client_id',
				'type'              => 'number',
				'instructions'      => __( 'The ID of the oAuth2.0 Client.', THEME_DOMAIN ),
				'required'          => 1,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5c0fde5a133b8',
							'operator' => '!=empty',
						),
					),
				),
			),
			array(
				'key'               => 'field_5c1634144d16e',
				'label'             => __( 'Group ID (default)', THEME_DOMAIN ),
				'name'              => 'group_id',
				'type'              => 'number',
				'instructions'      => __( 'The ID of the group, where <strong>new</strong> member records should be stored in.',
					THEME_DOMAIN ),
				'required'          => 1,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5c0fde5a133b8',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'min'               => 100,
				'max'               => '',
				'step'              => 1,
			),
			array(
				'key'               => 'field_5c1634144d17f',
				'label'             => __( 'Group ID (possible duplicates)', THEME_DOMAIN ),
				'name'              => 'group_id_duplicates',
				'type'              => 'number',
				'instructions'      =>
					__( 'The ID of the group, where <strong>possible duplicate</strong> member records should be stored in.', THEME_DOMAIN )
					. ' ' . __( 'If left empty, possible duplicates will be stored in the same group as new member records.', THEME_DOMAIN ),
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5c0fde5a133b8',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'min'               => 100,
				'max'               => '',
				'step'              => 1,
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'form-general-settings',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => 1,
		'description'           => '',
	) );

endif;
