<?php

if ( function_exists( 'acf_add_local_field_group' ) ):
	
	acf_add_local_field_group( array(
		'key'                   => 'group_5a880cad9baac',
		'title'                 => 'Settings',
		'fields'                => array(
			array(
				'key'               => 'field_5ab21eb2fe214',
				'label'             => 'E-mail addresses',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 1,
			),
			array(
				'key'               => 'field_5a880d8c10cc3',
				'label'             => '',
				'name'              => '',
				'type'              => 'message',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => 'The parameters below are global, but can be replaced specifically in the options of each form.',
				'new_lines'         => 'wpautop',
				'esc_html'          => 0,
			),
			array(
				'key'               => 'field_5a880e1a10cc4',
				'label'             => 'Destination',
				'name'              => 'form_email_to',
				'type'              => 'email',
				'instructions'      => 'This email address will receive notifications when a form is completed.',
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_5a880e6310cc5',
				'label'             => 'Sender',
				'name'              => 'form_email_from',
				'type'              => 'email',
				'instructions'      => 'E-mail address that will appear as sender.',
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_5a880ed310cc6',
				'label'             => 'Name',
				'name'              => 'form_name_from',
				'type'              => 'text',
				'instructions'      => 'This is the name that will appear as the sender.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5a880ff110cc8',
				'label'             => 'Templates',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 1,
			),
			array(
				'key'               => 'field_5a88145e726f1',
				'label'             => '',
				'name'              => '',
				'type'              => 'message',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => 'The email templates below use the <a href="https://twig.symfony.com/" target="_blank">template Twig</a> engine to allow dynamic zones.

	The dynamic fields available are identical to the field names of each form. i.e <strong>{{ firstname }}</strong> will be replaced by the value entered by the user.',
				'new_lines'         => 'wpautop',
				'esc_html'          => 0,
			),
			array(
				'key'               => 'field_5a8822c3c6318',
				'label'             => 'Notification',
				'name'              => 'form_notif',
				'type'              => 'group',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'row',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5a8822f4c6319',
						'label'             => 'Subject',
						'name'              => 'form_notif_subject',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => 'Website form notification',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
					array(
						'key'               => 'field_5a88100110cc9',
						'label'             => 'Template',
						'name'              => 'form_notif_template',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '<p>Hello,</p>

	<p>A new message from the {{ title }} form on the website.</p>

	<div><strong>Lastname</strong>: {{ lastname }}</div>
	<div><strong>Firstname</strong>: {{ firstname }}</div>
	<div><strong>Phone</strong>: {{ phone }}</div>
	<div><strong>E-mail</strong>: {{ email }}</div>

	<p><strong>Message:</strong><br/>{ message }}</p>',
						'tabs'              => 'all',
						'toolbar'           => 'basic',
						'media_upload'      => 1,
						'delay'             => 0,
					),
				),
			),
			array(
				'key'               => 'field_5a882319c631a',
				'label'             => 'Acknowledge of reception',
				'name'              => 'form_autoreply',
				'type'              => 'group',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'row',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5a882319c631b',
						'label'             => 'Subject',
						'name'              => 'form_autoreply_subject',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => 'Thank you for message',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
					array(
						'key'               => 'field_5a88103d10cca',
						'label'             => 'Template',
						'name'              => 'form_autoreply_template',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '<strong>Hello {{ firstname }} {{ lastname }},</strong>

	<p>Thank you for your interest.<br/>
	We acknowledge receipt of your message and will respond shortly.

	We send you our best regards.</p>

	<p>__________________<br/>The team</p>',
						'tabs'              => 'all',
						'toolbar'           => 'basic',
						'media_upload'      => 1,
						'delay'             => 0,
					),
				),
			),
			array(
				'key'               => 'field_5a9s2f6hc34da',
				'label'             => 'Privacy policy',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 1,
			),
			array(
				'key'               => 'field_5ab255fd48364',
				'label'             => 'Page',
				'name'              => 'form_privacy_page',
				'type'              => 'page_link',
				'instructions'      => 'Select the page with the privacy policy.',
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'post_type'         => array( 'post', 'page' ),
				'taxonomy'          => array(),
				'allow_null'        => 1,
				'allow_archives'    => 0,
				'multiple'          => 0,
			),
			array(
				'key'               => 'field_5ab26cadd4eeb',
				'label'             => 'Anti-spam',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 1,
			),
			array(
				'key'               => 'field_5a8b00baeaeac',
				'label'             => 'Active',
				'name'              => 'recaptcha_active',
				'type'              => 'true_false',
				'instructions'      => 'Protect your website from spam and abuse while allowing real people to pass easily, with <a href="https://www.google.com/recaptcha/" target="_blank">Google reCAPTCHA</a>.<br>Before you enable this protection, please register for an access to the API <a href="https://www.google.com/recaptcha/admin">here</a> and set the keys below.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'ui'                => 1,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
			),
			array(
				'key'               => 'field_5a8b00f3eaead',
				'label'             => 'Site key',
				'name'              => 'recaptcha_site_key',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 1,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5a8b00baeaeac',
							'operator' => '==',
							'value'    => '1',
						),
					),
				),
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5a8b0237eaeae',
				'label'             => 'Secret key',
				'name'              => 'recaptcha_secret_key',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 1,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5a8b00baeaeac',
							'operator' => '==',
							'value'    => '1',
						),
					),
				),
				'wrapper'           => array(
					'width' => '50',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5a95bda5c34da',
				'label'             => 'SMTP',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 1,
			),
			array(
				'key'               => 'field_5a95bdafc34db',
				'label'             => 'Enabled',
				'name'              => 'form_smtp_enabled',
				'type'              => 'true_false',
				'instructions'      => 'If yes, send emails via configured SMTP',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'ui'                => 1,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
			),
			array(
				'key'               => 'field_5a95bdf6c34dc',
				'label'             => '',
				'name'              => 'form_smtp',
				'type'              => 'group',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5a95bdafc34db',
							'operator' => '==',
							'value'    => '1',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'            => 'block',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5a95be01c34dd',
						'label'             => 'Server address',
						'name'              => 'host',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
					array(
						'key'               => 'field_5a95be3dc34de',
						'label'             => 'Port',
						'name'              => 'port',
						'type'              => 'number',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => 465,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'min'               => '',
						'max'               => '',
						'step'              => '',
					),
					array(
						'key'               => 'field_5a95be77c34df',
						'label'             => 'Username',
						'name'              => 'username',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '50',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
					array(
						'key'               => 'field_5a95be8fc34e0',
						'label'             => 'Password',
						'name'              => 'password',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '50',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
				),
			),
			array(
				'key'               => 'field_5a883da4b60ec',
				'label'             => 'Advanced',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 1,
			),
			array(
				'key'               => 'field_5a883dacb60ed',
				'label'             => 'Save to database',
				'name'              => 'form_save_db',
				'type'              => 'true_false',
				'instructions'      => 'If yes, the data of each form submission will be saved in the database and accessible via the submenu <strong>Sends</strong> of the menu <strong>Forms</strong>.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'ui'                => 1,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'form-general-settings',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => 1,
		'description'           => '',
	) );

endif;
