label: Events
status: ready
default: Full width
context:
  modifiers:
    - full-width
  cat-title:
    label: Events
  link-button:
    label: Alle Events anzeigen
    link: '#'
  events:
    - title: Öffentlichkeit und Demokratie im Zeitalter der Neuen Medien
      timestamp: '2018-08-25 11:00'
      datetime: 28. Oktober 2017 | 10:45 - 12:30
      place: Hotel & Restaurant Landgasthof, Baselstrasse 38, Riehen
      link-url: '#'
      image:
        image-src: "/img/dv.jpg"
        alt: Die Delegierten schreiten zur Abstimmung
        title: This is a linked image
    - title: Delegiertenversammlung mit Stargast mit sehr langem Namen
      timestamp: '2018-08-25 11:00'
      datetime: 25. August 2018 | 11:00
      place: Säulenhalle Zug
      link-url: '#'
      image:
        image-src: "/img/dv.jpg"
        alt: Die Delegierten schreiten zur Abstimmung
        title: This is a linked image
    - title: Netzwerktreffen Grüne Städte – voneinander lernen
      timestamp: '2018-08-25 11:00'
      datetime: 10. Juni 2017 | 10:15 - 16:45
      place: aki, Alpeneggstrasse 5, Bern
      link-url: '#'
      image:
        image-src: "/img/dv.jpg"
        alt: Die Delegierten schreiten zur Abstimmung
        title: This is a linked image
    - title: Delegiertenversammlung
      timestamp: '2018-08-25 11:00'
      datetime: 25. August 2018 – 11:00
      place: Säulenhalle Zug
      link-url: '#'
      image:
        image-src: "/img/dv.jpg"
        alt: Die Delegierten schreiten zur Abstimmung
        title: This is a linked image
variants:
  - name: Single column
    context:
      modifiers:
      -
