label: Bar
status: ready
default: green left
context:
  label: Kurz halten! ÖJ
  modifiers:
    - green
    - left
variants:
  - name: magenta left
    context:
      modifiers:
      - magenta
      - left
  - name: white left
    context:
      modifiers:
        - white
        - left
  - name: green right
    context:
      modifiers:
      - magenta
      - right
  - name: magenta right
    context:
      modifiers:
      - magenta
      - right
  - name: white right
    context:
      modifiers:
      - white
      - right
  - name: subline left
    context:
      modifiers:
      - white
      - left
      - subline
  - name: subline right
    context:
      modifiers:
        - white
        - right
        - subline