label: Button
status: ready
display:
  padding: 40px
context:
  label: Mitmachen
  class: added-class
variants:
  - name: Outlined
    context:
      modifiers:
        - outline
  - name: Secondary
    context:
      modifiers:
        - secondary
  - name: Secondary outlined
    context:
      modifiers:
        - secondary
        - outline
  - name: Transparent outlined
    display:
      background: "#E2E2E2"
    context:
      modifiers:
        - transparent
  - name: Full width
    context:
      modifiers:
        - full-width
  - name: Link
    context:
      url: 'https://google.com'
      target: '_blank'
      label: Google
