label: Share
status: ready
display:
  padding: 40px
context:
  label: partager
  icons:
  - link: "https://www.facebook.com/sharer.php?u=https%3A%2F%2Fcss-tricks.com%2F"
    type: facebook--no-outline
  - link: "https://twitter.com/intent/tweet?url=https%3A%2F%2Fcss-tricks.com%2F&text=Tips%2C+Tricks%2C+and+Techniques+on+using+Cascading+Style+Sheets.&hashtags=css,html"
    type: twitter--no-outline
  - link: "mailto:?subject=Sitetitle&body=Some%20content"
    type: mail--no-outline
  - link: "whatsapp://send?abid=BROADCAST_ID&text="
    type: whatsapp--no-outline
