label: Initiative link
status: ready
context:
  title: Klimaschutz jetzt
  subtitle: Für eine nachhaltige Zukunft in der Schweiz.
  link: '#'
  image:
    image-src: "/img/dv.jpg"
    alt: Initiative image
    title: This is a linked image
